name: untytled
favicon: null
layout_spectrum: 0.25964
typography_spectrum: 0.09586
title: untytled
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#929292'
    - '#9f9f9f'
    - '#696969'
    - '#b9b9b9'
    - '#515151'
  brandStrength: 0.6875
  lightness: 0.40547511633485556
  saturation: 0.39393714629113674
  rhythmicContrast: 0.5084599086549133
purpose: []
