name: untytled
favicon: null
layout_spectrum: 0.24334
typography_spectrum: 0.164
title: untytled
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#929292'
    - '#9f9f9f'
    - '#696969'
    - '#b9b9b9'
    - '#515151'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
